Added API docs
ixofoundation/ixo-cellnode pull request #88
Opened 2021-09-17 14:46 UTC by stefaniatadama

2021-09-17 14:50 UTC, migueldingli1997 requested changes

2021-09-17 14:50 UTC, migueldingli1997 commented on api.md
> +NOTE
Extra note

2021-09-17 14:50 UTC, migueldingli1997 commented on api.md
> +This document lists Cellnode's API endpoints and provides some examples of their usage. Since ixo-apimodule is another ixo component which interacts extensively with Cellnode and demonstrates its usa
```suggestion
This document lists Cellnode's API endpoints and provides some examples of their usage. Since ixo-apimodule is another ixo component which interacts extensively with Cellnode and demonstrates its usage in [demo.ts](https://github.com/ixofoundation/ixo-apimodule/blob/master/test/demo.ts), some documentation for ixo-apimodule is also provided here to illustrate their interactions.
```

2021-09-17 14:50 UTC, migueldingli1997 commented on api.md
> +# Cellnode API Documentation
Let's go with "Cell Node" throughout instead of Cellnode

2021-09-17 14:50 UTC, migueldingli1997 commented on api.md
> +Response: [ixo Explorer: listProjects](https://app.swaggerhub.com/apis-docs/drshaun/ixo/0.2.3#/projects/listProjects)
I suggest we go with `ixo-blocksync` throughout instead of `ixo Explorer`:
```suggestion
Response: [ixo-blocksync: listProjects](https://app.swaggerhub.com/apis-docs/drshaun/ixo/0.2.3#/projects/listProjects) 
```

2021-09-17 14:50 UTC, migueldingli1997 commented on api.md
> +Updates a project's current status.
Let's put a blank line after each title for consistency:
```suggestion
#### Update Project Status

Updates a project's current status.
```

2021-09-17 14:50 UTC, migueldingli1997 commented on api.md
> +
```suggestion

Usage:
```

2021-09-17 14:52 UTC, migueldingli1997 commented on api.md
> +The ixo-cellNode \(cellnode\) uses JSON-RPC to receive client requests. The structure of all calls follow the same structure:
Something missing after this

2021-09-17 15:13 UTC, migueldingli1997 approved these changes

2021-09-23 14:08 UTC, migueldingli1997 commented on api.md
> +Response: [ixo Blockchain: getDidDoc](https://app.swaggerhub.com/#/Query/DidDoc)
I don't think this link is correct

2021-09-23 14:11 UTC, stefaniatadama commented on api.md
> +Response: [ixo Blockchain: getDidDoc](https://app.swaggerhub.com/#/Query/DidDoc)
You are right

2021-09-23 14:15 UTC, merged